/*
Assets - Deadlock API

Testing RawAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package assets_deadlock_api_client

import (
	"context"
	"testing"

	openapiclient "github.com/NickGroveSE/openapi-clients-deadlock/go/assets-api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_assets_deadlock_api_client_RawAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RawAPIService GetGenericDataRawGenericDataGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RawAPI.GetGenericDataRawGenericDataGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RawAPIService GetRawHeroesRawHeroesGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RawAPI.GetRawHeroesRawHeroesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RawAPIService GetRawItemsRawItemsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RawAPI.GetRawItemsRawItemsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
