/*
Deadlock API

Testing BuildsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package deadlock_api_client

import (
	"context"
	"testing"

	openapiclient "github.com/NickGroveSE/openapi-clients-deadlock/go/api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_deadlock_api_client_BuildsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BuildsAPIService SearchBuilds", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.BuildsAPI.SearchBuilds(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
